# Generated by Django 5.1 on 2024-09-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correct_solution',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answer_text',
        ),
    ]
