# Generated by Django 5.1 on 2024-09-13 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exercise_correct_solution_submission_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
